# Generated by Django 4.0.3 on 2022-03-17 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('photo', models.FileField(upload_to='kyc/bank/%Y/%m/%d')),
                ('id_proof', models.FileField(upload_to='kyc/id/%Y/%m/%d')),
                ('bank_statement', models.FileField(upload_to='kyc/alt/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('landmark', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=100)),
                ('emergency_phone_number', models.CharField(max_length=30)),
                ('expired_time', models.DateTimeField(blank=True, null=True)),
                ('occupation', models.CharField(max_length=30)),
                ('organiization', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Education Loan', 'education_loan'), ('Home Loan', 'home_loan'), ('Travel Loan', 'travel_loan'), ('Medical Loan', 'medical_loan'), ('Other', 'other')], max_length=100)),
                ('loan_amount', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('interest_rate', models.CharField(max_length=5)),
                ('emi_amount', models.CharField(max_length=20)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proofs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proof', models.FileField(upload_to='documents/id/%Y/%m/%d')),
                ('govt_id', models.FileField(upload_to='documents/govtid/%Y/%m/%d')),
                ('bank_statement', models.FileField(upload_to='documents/alt/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.CharField(choices=[('lender', 'lender'), ('borrower', 'borrower')], max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.state'),
        ),
    ]
