# Generated by Django 4.0.3 on 2022-03-17 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_application',
            old_name='emergency_phone_number',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='loan_application',
            name='expired_time',
        ),
        migrations.RemoveField(
            model_name='loan_application',
            name='organiization',
        ),
        migrations.AddField(
            model_name='loan_application',
            name='accepted',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('in_review', 'in_review')], default='in_review', max_length=100),
        ),
        migrations.AddField(
            model_name='proofs',
            name='alt_data',
            field=models.FileField(default=None, upload_to='documents/alt/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='proofs',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan_application',
            name='landmark',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='proofs',
            name='bank_statement',
            field=models.FileField(upload_to='documents/bank/%Y/%m/%d'),
        ),
    ]
