# Generated by Django 4.0.3 on 2022-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_emergency_phone_number_loan_application_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_application',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan_application',
            name='category',
            field=models.CharField(choices=[('Education Loan', 'education_loan'), ('Home Loan', 'home_loan'), ('Business Loan', 'business_loan'), ('Medical Loan', 'medical_loan'), ('Other', 'other')], max_length=100),
        ),
    ]
