# Generated by Django 4.0.3 on 2022-03-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_userprofile_credit_limit_userprofile_credit_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Education Loan', 'education_loan'), ('Home Loan', 'home_loan'), ('Business Loan', 'business_loan'), ('Medical Loan', 'medical_loan'), ('Other', 'other')], max_length=100)),
                ('loan_amount', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('interest_rate', models.CharField(max_length=5)),
                ('emi_amount', models.CharField(max_length=20)),
                ('accepted', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('accepted_date', models.DateTimeField(auto_now=True)),
                ('last_repayment_date', models.DateTimeField(auto_now=True)),
                ('emi_number', models.CharField(max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
